# Generated by Django 6.0.1 on 2026-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='size_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
