# Generated by Django 6.0.1 on 2026-03-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0002_alter_item_model_date_alter_size_model_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_model',
            options={'ordering': ['created_at'], 'verbose_name': 'Item Model', 'verbose_name_plural': 'Item Models'},
        ),
        migrations.AlterModelOptions(
            name='size_model',
            options={'ordering': ['created_at'], 'verbose_name': 'Size Model', 'verbose_name_plural': 'Size Models'},
        ),
    ]
