# Generated by Django 6.0.1 on 2026-03-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0003_alter_item_model_options_alter_size_model_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_model_created', to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='mgmt_system.item_model')),
            ],
            options={
                'verbose_name': 'Vendor Model',
                'verbose_name_plural': 'Vendor Models',
                'ordering': ['id'],
            },
        ),
    ]
