# Generated by Django 6.0.1 on 2026-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0004_vendor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_model',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
