# Generated by Django 6.0.1 on 2026-03-11 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0006_alter_item_model_date_alter_size_model_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaxReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wax_receive_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wax_receives', to='mgmt_system.vendor_model')),
            ],
            options={
                'verbose_name': 'Wax Receive',
                'verbose_name_plural': 'Wax Receives',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WaxReceiveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('in_quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wax_receive_lines', to='mgmt_system.item_model')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wax_receive_lines', to='mgmt_system.size_model')),
                ('wax_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mgmt_system.waxreceive')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
