# Generated by Django 6.0.1 on 2026-03-11 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0007_waxreceive_waxreceiveline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('out_quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_master_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='mgmt_system.item_model')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='mgmt_system.size_model')),
            ],
            options={
                'verbose_name': 'Issue Master',
                'verbose_name_plural': 'Issue Masters',
                'ordering': ['id'],
            },
        ),
    ]
