# Generated by Django 6.0.1 on 2026-03-14

from django.conf import settings
from django.db import migrations, models


def forwards_create_vendor_list(apps, schema_editor):
    VendorList = apps.get_model("mgmt_system", "VendorList_Model")
    VendorModel = apps.get_model("mgmt_system", "Vendor_Model")
    db_alias = schema_editor.connection.alias

    # Create unique vendor list entries from existing vendor_name column
    vendor_names = (
        VendorModel.objects.using(db_alias)
        .values_list("vendor_name", flat=True)
        .distinct()
    )
    name_to_id = {}
    for name in vendor_names:
        if not name:
            continue
        vendor_obj = VendorList.objects.using(db_alias).create(vendor_name=name)
        name_to_id[name] = vendor_obj.id

    # Backfill vendor FK
    for vendor in VendorModel.objects.using(db_alias).all():
        if vendor.vendor_name in name_to_id:
            vendor.vendor_id = name_to_id[vendor.vendor_name]
            vendor.save(update_fields=["vendor"])


def backwards_delete_vendor_list(apps, schema_editor):
    VendorList = apps.get_model("mgmt_system", "VendorList_Model")
    VendorList.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mgmt_system", "0008_issuemaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorList_Model",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="vendor_list_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor List",
                "verbose_name_plural": "Vendor Lists",
                "ordering": ["vendor_name"],
            },
        ),
        migrations.AddField(
            model_name="vendor_model",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name="vendor_rates",
                to="mgmt_system.vendorlist_model",
            ),
        ),
        migrations.RunPython(forwards_create_vendor_list, backwards_delete_vendor_list),
        migrations.RemoveField(
            model_name="vendor_model",
            name="vendor_name",
        ),
        migrations.AlterField(
            model_name="vendor_model",
            name="vendor",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="vendor_rates",
                to="mgmt_system.vendorlist_model",
            ),
        ),
    ]
