# Generated by Django 6.0.1 on 2026-03-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0008_issuemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizemodelhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sizemodelhistory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sizemodelhistory',
            name='size_model',
        ),
        migrations.RemoveField(
            model_name='vendormodelhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendormodelhistory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='vendormodelhistory',
            name='vendor_model',
        ),
        migrations.DeleteModel(
            name='ItemModelHistory',
        ),
        migrations.DeleteModel(
            name='SizeModelHistory',
        ),
        migrations.DeleteModel(
            name='VendorModelHistory',
        ),
    ]
