# Generated by Django 6.0.1 on 2026-03-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0015_waxreceiveline_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waxreceive',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wax_receives', to='mgmt_system.vendorlist_model'),
        ),
    ]
