# Generated by Django 6.0.1 on 2026-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0016_alter_waxreceive_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockmanagement_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorlist_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waxreceive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waxreceiveline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
