# Generated by Django 6.0.1 on 2026-03-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_system', '0017_issuemaster_is_active_item_model_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedRecord',
        ),
    ]
