# Generated by Django 6.0.1 on 2026-03-09 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(choices=[('vendor_master', 'Vendor-Master'), ('item_master', 'Item-Master'), ('size_master', 'Size-Master'), ('wax_receive', 'Wax-Receive'), ('issue_master', 'Issue-Master'), ('stock_management', 'StockManagement')], max_length=50)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['master_name'],
                'unique_together': {('user', 'master_name')},
            },
        ),
    ]
