# Generated by Django 6.0.1 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_mgmt", "0002_masterpermission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="masterpermission",
            old_name="can_write",
            new_name="can_create_update",
        ),
        migrations.AddField(
            model_name="masterpermission",
            name="can_delete",
            field=models.BooleanField(default=False),
        ),
    ]
