# Generated by Django 6.0.1 on 2026-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mgmt', '0003_masterpermission_access_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpermission',
            name='master_name',
            field=models.CharField(choices=[('vendor_master', 'Vendor-Master'), ('item_master', 'Item-Master'), ('size_master', 'Size-Master'), ('wax_receive', 'Wax-Receive'), ('issue_master', 'Issue-Master'), ('stock_management', 'StockManagement'), ('deleted_records', 'Deleted Records')], max_length=50),
        ),
    ]
